function [f,x] = f_myfile(x)
%F_MYFILE
%    [F,X] = F_MYFILE(X)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    13-Sep-2021 20:05:19

f = cos(x)+x.^2.*3.0;
if nargout > 1
    x = x;
end
