function out1 = fg_myfile(x,y)
%FG_MYFILE
%    OUT1 = FG_MYFILE(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    13-Sep-2021 20:05:20

out1 = [cos(x)+x.^2.*3.0;exp(-y.^2)];
